function initButtons(){function b(){$(this).bind("mouseout",function(){$(this).html("")})}function c(){$(this).unbind({mouseover:b,click:c}).removeClass("dump").addClass("dumped").bind({mouseover:e,click:f});rowIndex=$(this).prop("rowIndex");gainNodeArray[rowIndex].disconnect();gainNodeArray[rowIndex].connect(context.destination);fxOnArray[rowIndex]=0}function e(){$(this).html("")}function f(){$(this).unbind({mouseover:e,click:f}).removeClass("dumped").addClass("dump").bind({mouseover:b,click:c});
connectTheFX($(this).prop("rowIndex"));fxOnArray[$(this).prop("rowIndex")]=1}$(".dismiss").bind("click",function(){$(".overlay").animate({opacity:0,left:"100%"},500);$(".blocker").animate({opacity:0},500);window.setTimeout(function(){$(".overlay").hide();$(".blocker").hide()},500)});$(".volume").each(function(a){$(this).attr("value",100*volumeArray[a]).change(function(){that=$(this);var b=that.val()/that.attr("max");volumeArray[a]=b;gainNodeArray[a].gain.value=b;muteArray[a]=1;$(getTheMuteButton(a))&&
$(getTheMuteButton(a)).removeClass("muted").addClass("mute")})});$(".bpm").change(function(){bpm=$(this).val();forStringification=1*bpm;stringified=forStringification.toFixed(2);$("#tempoLabel").html("TEMPO: "+stringified+"bpm")});$(".swing").change(function(){swingLevel=$(this).val()});$(".delayFeedbackGain").each(function(){$(this).change(function(){that=$(this);var a=that.val()/that.attr("max");feedbackGainArray[showPattern]=a;feedbackGainNodeArray[showPattern].gain.value=a;toBeStringified=100*
a;forString=toBeStringified.toFixed(0);$("#delayFeedback").html("Feedback: "+forString+"%")})});$(".delayTime").each(function(){$(this).change(function(){that=$(this);var a=that.val()/that.attr("max");delayTimeArray[showPattern]=a;delayArray[showPattern].delayTime.value=a;$("#delayTime").html("Time: "+a+"s")})});$(".filterFreq").each(function(){$(this).change(function(){that=$(this);var a=context.sampleRate/2,b=Math.log(that.attr("max")/that.attr("min"))/Math.LN2,b=Math.pow(2,b*(that.val()-1)),a=
a*b;filterFreqArray[showPattern]=a;filterArray[showPattern].frequency.value=a;forString=a.toFixed(0);$("#filterFrequency").html("Freq: "+forString+"hz")})});$(".filterQ").each(function(){$(this).change(function(){that=$(this);var a=5*that.val();filterQArray[showPattern]=a;filterArray[showPattern].Q.value=a;toBeStringified=2*a;forString=toBeStringified.toFixed(0);$("#filterQ").html("Q: "+forString+"%")})});$(".overdriveFeedback").each(function(){$(this).change(function(){that=$(this);var a=that.val();
overdriveFeedbackArray[showPattern]=a;overdriveArray[showPattern].gain.value=a;toBeStringified=100*(a/0.95);forString=toBeStringified.toFixed(0);$("#overdriveFeedback").html("Amount: "+forString+"%")})});$(".dump").bind({mouseover:b,click:c});$("#fx0").bind("click",function(){delayOnArray[showPattern]?(delayOnArray[showPattern]=0,$(this).removeClass("fx").addClass("activeFx"),$("#delayOn").html("Delay: Off")):(delayOnArray[showPattern]=1,$(this).addClass("fx").removeClass("activeFx"),$("#delayOn").html("Delay: On"));
connectTheFX(showPattern)});$("#fx1").bind("click",function(){filterOnArray[showPattern]?(filterOnArray[showPattern]=0,$(this).removeClass("fx").addClass("activeFx"),$("#filterOn").html("Filter: Off")):(filterOnArray[showPattern]=1,$(this).addClass("fx").removeClass("activeFx"),$("#filterOn").html("Filter: On"));connectTheFX(showPattern)});$("#fx2").bind("click",function(){overdriveOnArray[showPattern]?(overdriveOnArray[showPattern]=0,$(this).removeClass("fx").addClass("activeFx"),$("#overdriveOn").html("Overdrive: Off")):
(overdriveOnArray[showPattern]=1,$(this).addClass("fx").removeClass("activeFx"),$("#overdriveOn").html("Overdrive: On"));connectTheFX(showPattern)});$("#fx3").bind("click",function(){fxOnArray[showPattern]?(fxOnArray[showPattern]=0,$(this).removeClass("fx").addClass("activeFx"),gainNodeArray[showPattern].disconnect(),gainNodeArray[showPattern].connect(context.destination),$("#fxOn").html("Effects: Off")):(fxOnArray[showPattern]=1,$(this).addClass("fx").removeClass("activeFx"),connectTheFX(showPattern),
$("#fxOn").html("Effects: On"))});$("#switcher0").prop("patternIndex",8).bind("click",function(){$("#drumPattern1").hide();$("#drumPattern2").show();showPattern=$(this).prop("patternIndex");initPattern(1)});for(var d=0;d<$(".switcher").length;d++)$($(".switcher")[d]).prop("patternIndex",d).bind("click",function(){$("#drumPattern2").hide();$("#drumPattern1").show();showPattern=$(this).prop("patternIndex");initPattern(0)});$(".mute").each(function(a){$(this).prop("rowIndex",a).bind({click:muteCall,
mouseover:showMuteLabel})});$(".playPause").each(function(){$(this).bind({click:handlePlay,mouseover:showLabel})})}function handlePlay(){isPlaying=1;$(this).html("");$(".playPause").each(function(){$(this).unbind("click",handlePlay).bind("click",handlePause).removeClass("playPause").addClass("pause")});stepTime=0;startTime=context.currentTime+0.005;$(stepIndexArray).each(function(b){stepIndexArray[b]=startLoopArray[b]});nextSchedule()}
function handlePause(){isPlaying=0;$(this).html("");$(".pause").each(function(){$(this).unbind("click",handlePause).bind("click",handlePlay).removeClass("pause").addClass("playPause")});clearTimeout(clock);for(var b=0;20>b;b++)12>b?(currentButton=getTheButton(b,lastStepArray[showPattern]+1),allRhythms[showPattern][b][lastStepArray[showPattern]+1]||$(currentButton).removeClass("active")):isMiniLooping[b-12]?(currentButton=getTheButton(b,lastStepArray[b-12]+1),$(currentButton).removeClass("active").addClass("loop")):
(currentButton=getTheButton(b,lastStepArray[b-12]+1),$(currentButton).removeClass("active"))}function showLabel(){$(this).html("").unbind("mouseover",showLabel).bind("mouseout",hideLabel)}function hideLabel(){$(this).html("").unbind("mouseout",hideLabel).bind("mouseover",showLabel)}
function muteCall(){muteArray[$(this).prop("rowIndex")]?(muteArray[$(this).prop("rowIndex")]=0,gainNodeArray[$(this).prop("rowIndex")].gain.value=0,$(this).removeClass("mute").addClass("muted")):(muteArray[$(this).prop("rowIndex")]=1,gainNodeArray[$(this).prop("rowIndex")].gain.value=volumeArray[$(this).prop("rowIndex")],$(this).html("").removeClass("muted").addClass("mute"))}
function showMuteLabel(){$(this).unbind("mouseover",showMuteLabel).bind("mouseout",hideMuteLabel);muteArray[$(this).prop("rowIndex")]&&$(this).html("")}function hideMuteLabel(){$(this).unbind("mouseout",hideMuteLabel).bind("mouseover",showMuteLabel);$(this).html("")}
function stepToggle(){$(window).bind("mouseup",stopToggling);for(var b=0;b<rowA.length;b++)for(var c=0;c<a7Array.length;c++)bindToThese=getTheButton(b,c),$(bindToThese).bind({mouseover:lightItUp,mouseup:stopToggling});allRhythms[showPattern][$(this).prop("rowIndex")][$(this).prop("columnIndex")]?(allRhythms[showPattern][$(this).prop("rowIndex")][$(this).prop("columnIndex")]=0,$(this).removeClass("active"),turnOnOrOff=1):(allRhythms[showPattern][$(this).prop("rowIndex")][$(this).prop("columnIndex")]=
1,$(this).addClass("active"),turnOnOrOff=0)};