var context,a0,aSharp0,b0,c0,cSharp0,d0,dSharp0,e0,f0,fSharp0,g0,gSharp0,a1,aSharp1,b1,c1,cSharp1,d1,dSharp1,e1,f1,fSharp1,g1,gSharp1,a2,aSharp2,b2,c2,cSharp2,d2,dSharp2,e2,f2,fSharp2,g2,gSharp2,a3,aSharp3,b3,c3,cSharp3,d3,dSharp3,e3,f3,fSharp3,g3,gSharp3,a4,aSharp4,b4,c4,cSharp4,d4,dSharp4,e4,f4,fSharp4,g4,gSharp4,a5,aSharp5,b5,c5,cSharp5,d5,dSharp5,e5,f5,fSharp5,g5,gSharp5,a6,aSharp6,b6,c6,cSharp6,d6,dSharp6,e6,f6,fSharp6,g6,gSharp6,a7,aSharp7,b7,c7,cSharp7,d7,dSharp7,e7,f7,fSharp7,g7,gSharp7,a0Array=
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp0Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b0Array=[0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0],c0Array=[1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0],cSharp0Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d0Array=[0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0],dSharp0Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0],e0Array=[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],f0Array=[0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],fSharp0Array=[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],g0Array=[0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],gSharp0Array=[0,0,1,0,0,0,0,
0,0,0,0,0,0,1,0,0],a1Array=[0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0],aSharp1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],c1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp1Array=[0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0],d1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e1Array=[0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0],f1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],fSharp1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],g1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
gSharp1Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],a2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b2Array=[0,1,0,0,0,0,0,1,0,1,1,1,0,0,0,0],c2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp2Array=[0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],e2Array=[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],f2Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],fSharp2Array=[0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0],g2Array=[0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0],gSharp2Array=[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],a3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp3Array=[0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0],b3Array=[0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],c3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],f3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],fSharp3Array=[0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0],g3Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],gSharp3Array=[0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0],a4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp4Array=[0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0],b4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],c4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],f4Array=[0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1],fSharp4Array=
[1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0],g4Array=[0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0],gSharp4Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],a5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],c5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp5Array=[0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0],e5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],f5Array=[0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0],fSharp5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],g5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],gSharp5Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],a6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],aSharp6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b6Array=[1,1,1,0,1,1,0,0,1,1,1,0,1,0,0,1],c6Array=[0,0,0,1,0,0,1,1,0,0,0,1,0,1,1,0],cSharp6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
f6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],fSharp6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],g6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],gSharp6Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],a7Array=[1,0,0,1,1,0,0,0,1,0,0,1,1,1,0,0],aSharp7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],b7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],c7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],cSharp7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],d7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],dSharp7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],e7Array=[0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0],f7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],fSharp7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],g7Array=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],gSharp7Array=[1,0,0,1,1,0,0,0,1,0,0,1,0,1,1,0];sampleBank0=[gSharp0,g0,fSharp0,f0,e0,dSharp0,d0,cSharp0,c0,b0,aSharp0,a0];sampleBank1=[gSharp1,g1,fSharp1,f1,e1,dSharp1,d1,cSharp1,c1,b1,aSharp1,a1];sampleBank2=[gSharp2,g2,fSharp2,f2,e2,dSharp2,d2,cSharp2,c2,b2,aSharp2,a2];
sampleBank3=[gSharp3,g3,fSharp3,f3,e3,dSharp3,d3,cSharp3,c3,b3,aSharp3,a3];sampleBank4=[gSharp4,g4,fSharp4,f4,e4,dSharp4,d4,cSharp4,c4,b4,aSharp4,a4];sampleBank5=[gSharp5,g5,fSharp5,f5,e5,dSharp5,d5,cSharp5,c5,b5,aSharp5,a5];sampleBank6=[gSharp6,g6,fSharp6,f6,e6,dSharp6,d6,cSharp6,c6,b6,aSharp6,a6];sampleBank7=[gSharp7,g7,fSharp7,f7,e7,dSharp7,d7,cSharp7,c7,b7,aSharp7,a7];allSamples=[sampleBank0,sampleBank1,sampleBank2,sampleBank3,sampleBank4,sampleBank5,sampleBank6,sampleBank7];
blankArray=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];
var rhythmArray0=[gSharp0Array,g0Array,fSharp0Array,f0Array,e0Array,dSharp0Array,d0Array,cSharp0Array,c0Array,b0Array,aSharp0Array,a0Array],rhythmArray1=[gSharp1Array,g1Array,fSharp1Array,f1Array,e1Array,dSharp1Array,d1Array,cSharp1Array,c1Array,b1Array,aSharp1Array,a1Array],rhythmArray2=[gSharp2Array,g2Array,fSharp2Array,f2Array,e2Array,dSharp2Array,d2Array,cSharp2Array,c2Array,b2Array,aSharp2Array,a2Array],rhythmArray3=[gSharp3Array,g3Array,fSharp3Array,f3Array,e3Array,dSharp3Array,d3Array,cSharp3Array,
c3Array,b3Array,aSharp3Array,a3Array],rhythmArray4=[gSharp4Array,g4Array,fSharp4Array,f4Array,e4Array,dSharp4Array,d4Array,cSharp4Array,c4Array,b4Array,aSharp4Array,a4Array],rhythmArray5=[gSharp5Array,g5Array,fSharp5Array,f5Array,e5Array,dSharp5Array,d5Array,cSharp5Array,c5Array,b5Array,aSharp5Array,a5Array],rhythmArray6=[gSharp6Array,g6Array,fSharp6Array,f6Array,e6Array,dSharp6Array,d6Array,cSharp6Array,c6Array,b6Array,aSharp6Array,a6Array],rhythmArray7=[gSharp7Array,g7Array,fSharp7Array,f7Array,
e7Array,dSharp7Array,d7Array,cSharp7Array,c7Array,b7Array,aSharp7Array,a7Array],rhythmArrayBlank=[blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray,blankArray],allRhythms=[rhythmArray0,rhythmArray1,rhythmArray2,rhythmArray3,rhythmArray4,rhythmArray5,rhythmArray6,rhythmArray7,rhythmArrayBlank];stepIndexArray=[0,0,0,0,0,0,0,0];lastStepArray=[15,15,15,15,15,15,15,15];startLoopArray=[0,0,0,0,0,0,0,0];
endLoopArray=[15,15,15,15,15,15,15,15];
var bpm=260,eighthNoteTime=60/bpm,maxSwing=eighthNoteTime/6,stepIndex=0,stepTime=0,startTime,clock,swingLevel=0.6,swingStepIndex=0,isBeingDraggedIn=[!1,!1,!1,!1,!1,!1,!1,!1],isMiniLooping=[!1,!1,!1,!1,!1,!1,!1,!1],workingMiniLoop=[],miniLoops=[miniLoopA,miniLoopB,miniLoopC,miniLoopD,miniLoopE,miniLoopF,miniLoopG,miniLoopH],miniLoopA=[],miniLoopB=[],miniLoopC=[],miniLoopD=[],miniLoopE=[],miniLoopF=[],miniLoopG=[],miniLoopH=[],gain0,gain1,gain2,gain3,gain4,gain5,gain6,gain7,gainNodeArray=[gain0,gain1,
gain2,gain3,gain4,gain5,gain6,gain7],delayFeedbackGain0,delayFeedbackGain1,delayFeedbackGain2,delayFeedbackGain3,delayFeedbackGain4,delayFeedbackGain5,delayFeedbackGain6,delayFeedbackGain7,feedbackGainNodeArray=[delayFeedbackGain0,delayFeedbackGain1,delayFeedbackGain2,delayFeedbackGain3,delayFeedbackGain4,delayFeedbackGain5,delayFeedbackGain6,delayFeedbackGain7],delay0,delay1,delay2,delay3,delay4,delay5,delay6,delay7,delayArray=[delay0,delay1,delay2,delay3,delay4,delay5,delay6,delay7],filter0,filter1,
filter2,filter3,filter4,filter5,filter6,filter7,filterArray=[filter0,filter1,filter2,filter3,filter4,filter5,filter6,filter7],overdrive0,overdrive1,overdrive2,overdrive3,overdrive4,overdrive5,overdrive6,overdrive7,overdriveArray=[overdrive0,overdrive1,overdrive2,overdrive3,overdrive4,overdrive5,overdrive6,overdrive7];feedbackGainArray=[0.75,0.25,0.1,0.35,0.35,0.45,0.75,0.01];delayTimeArray=[0.22,0.25,0.1,0.05,0.5,0.01,0.01,0.01];
var volumeArray=[0.8,0.1,0.8,0.2,0.75,0.9,0.85,0.8],filterFreqArray=[1165,1E3,330,2E3,2E3,4800,4500,4500],filterQArray=[25,0,0.01,1.5,0.3,0,0,0],filterTypeArray=[0,0,0,0,0,0,0,0],overdriveFeedbackArray=[0,0,0,0,0,0,0,0.95],fxOnArray=[1,1,1,1,1,1,1,1],muteArray=[1,1,1,1,1,1,1,1],delayOnArray=[1,1,1,1,0,1,1,0],filterOnArray=[1,1,1,1,1,1,1,1],overdriveOnArray=[0,1,1,1,1,1,1,1],showPattern=8,lightToTurnOff,turnOnOrOff,turnOffThisRow,mightJumpToHere,rowAffected,isPlaying=0;
$(document).ready(function(){try{context=new webkitAudioContext,$(".overlay").animate({left:"25%",opacity:1},1E3),$(".blocker").animate({opacity:0.75},1500),init(),initButtons(),$("#drumPattern1").hide()}catch(a){alert("Web Audio API is not supported in this browser. Download Google Chrome to take advantage of Step Sync's features.")}bufferLoader=new BufferLoader(context,"audio/a3.wav audio/aSharp3.wav audio/b3.wav audio/c3.wav audio/cSharp3.wav audio/d3.wav audio/dSharp3.wav audio/e3.wav audio/f3.wav audio/fSharp3.wav audio/g3.wav audio/gSharp3.wav audio/a4.wav audio/aSharp4.wav audio/b4.wav audio/c4.wav audio/cSharp4.wav audio/d4.wav audio/dSharp4.wav audio/e4.wav audio/f4.wav audio/fSharp4.wav audio/g4.wav audio/gSharp4.wav audio/a5.wav audio/aSharp5.wav audio/b5.wav audio/c5.wav audio/cSharp5.wav audio/d5.wav audio/dSharp5.wav audio/e5.wav audio/f5.wav audio/fSharp5.wav audio/g5.wav audio/gSharp5.wav audio/twinkleTwinkle00.wav audio/twinkleTwinkle01.wav audio/twinkleTwinkle02.wav audio/twinkleTwinkle03.wav audio/twinkleTwinkle04.wav audio/twinkleTwinkle05.wav audio/twinkleTwinkle06.wav audio/twinkleTwinkle07.wav audio/twinkleTwinkle08.wav audio/twinkleTwinkle09.wav audio/twinkleTwinkle10.wav audio/twinkleTwinkle11.wav audio/a8.wav audio/aSharp8.wav audio/b8.wav audio/c8.wav audio/cSharp8.wav audio/d8.wav audio/dSharp8.wav audio/e8.wav audio/f8.wav audio/fSharp8.wav audio/g8.wav audio/gSharp8.wav".split(" "),
finishedLoading);bufferLoader.load()});
function connectTheFX(a){gainNodeArray[a].disconnect();filterArray[a].disconnect();delayArray[a].disconnect();filterOnArray[a]?(gainNodeArray[a].connect(filterArray[a]),filterArray[a].connect(context.destination),filterArray[a].connect(delayArray[a])):(gainNodeArray[a].connect(context.destination),gainNodeArray[a].connect(delayArray[a]));overdriveOnArray[a]&&(gainNodeArray[a].connect(overdriveArray[a]),overdriveArray[a].connect(gainNodeArray[a]));delayOnArray[a]&&(delayArray[a].connect(feedbackGainNodeArray[a]),
feedbackGainNodeArray[a].connect(delayArray[a]),delayArray[a].connect(context.destination))}
function init(){$(".dump").each(function(a){$(this).prop("rowIndex",a)});for(var a=0;a<allSamples.length;a++)for(var b=0;b<sampleBank0.length;b++)allSamples[a][b]=context.createBufferSource();$(gainNodeArray).each(function(a){gainNodeArray[a]=context.createGainNode();gainNodeArray[a].gain.value=volumeArray[a];feedbackGainNodeArray[a]=context.createGainNode();feedbackGainNodeArray[a].gain.value=feedbackGainArray[a];delayArray[a]=context.createDelayNode();delayArray[a].delayTime.value=delayTimeArray[a];
filterArray[a]=context.createBiquadFilter();filterArray[a].frequency.value=filterFreqArray[a];overdriveArray[a]=context.createGainNode();overdriveArray[a].gain.value=overdriveFeedbackArray[a]});startTime=context.currentTime+0.005;for(a=0;20>a;a++)for(b=0;16>b;b++)currentButton=getTheButton(a,b),12>a?$(currentButton).prop("rowIndex",a).prop("columnIndex",b).bind("mousedown",stepToggle):$(currentButton).prop("rowIndex",a-12).prop("columnIndex",b).bind({click:stepJump,mousedown:startRowDrag})}
function finishedLoading(a){for(var b=0,c=0;c<allSamples.length;c++)for(var d=0;d<sampleBank0.length;d++)48>b?(allSamples[c][d]=a[b],b++):(allSamples[c][d]=a[b],59===b?b=48:b++);$(gainNodeArray).each(function(a){connectTheFX(a)})}
function nextSchedule(){currentTime=context.currentTime;currentTime-=startTime;for(nextStep=currentTime+eighthNoteTime;stepTime<currentTime+0.04;){for(var a=stepTime+startTime,b=0;b<allRhythms.length;b++)for(var c=0;c<rhythmArray0.length;c++)allRhythms[b][c][stepIndexArray[b]]&&playSound(allSamples[b][Math.abs(c-11)],a,b);advanceStep()}clock=setTimeout("nextSchedule()",0)}function playSound(a,b,c){var d=context.createBufferSource();d.buffer=a;d.connect(gainNodeArray[c]);d.noteOn(b)}
function advanceStep(){eighthNoteTime=60/bpm;var a=maxSwing*swingLevel;stepTime=0===swingStepIndex%2?stepTime+(eighthNoteTime+a):stepTime+(eighthNoteTime-a);updateLights();swingStepIndex++;for(a=0;a<stepIndexArray.length;a++)stepIndexArray[a]!=endLoopArray[a]?stepIndexArray[a]++:stepIndexArray[a]=startLoopArray[a]}
function lightItUp(){turnOnOrOff?(allRhythms[showPattern][$(this).prop("rowIndex")][$(this).prop("columnIndex")]=0,$(this).removeClass("active")):(allRhythms[showPattern][$(this).prop("rowIndex")][$(this).prop("columnIndex")]=1,$(this).addClass("active"))}function stopToggling(){$(window).unbind("mouseup",stopToggling);for(var a=0;a<rowA.length;a++)for(var b=0;b<a7Array.length;b++)bindToThese=getTheButton(a,b),$(bindToThese).unbind("mouseover",lightItUp).unbind("mouseup",stopToggling)}
function updateLights(){for(var a=0;20>a;a++)if(12>a){if(stepIndexArray[a]<startLoopArray[a]||stepIndexArray[a]>endLoopArray[a])currentButton=getTheButton(a,stepIndexArray[a-12]),currentButton.removeClass("active"),-1!=workingMiniLoop.indexOf(stepIndexArray[a])&&currentButton.addClass("loop");lastStepArray[a]=stepIndexArray[a]-1;if(-1===lastStepArray[a]||lastStepArray[a]===startLoopArray[a]-1&&isMiniLooping[a])lastStepArray[a]=endLoopArray[a];for(var b=0;b<rhythmArray4.length;b++)lastButton=getTheButton(b,
lastStepArray[showPattern]),currentButton=getTheButton(b,stepIndexArray[showPattern]),!allRhythms[showPattern][b][stepIndexArray[showPattern]]&&!allRhythms[showPattern][b][lastStepArray[showPattern]]?($(currentButton).addClass("active"),$(lastButton).removeClass("active").addClass("punch")):!allRhythms[showPattern][b][stepIndexArray[showPattern]]&&allRhythms[showPattern][b][lastStepArray[showPattern]]?$(currentButton).addClass("active"):allRhythms[showPattern][b][stepIndexArray[showPattern]]&&!allRhythms[showPattern][b][lastStepArray[showPattern]]&&
$(lastButton).removeClass("active").addClass("punch")}else if(currentButton=getTheButton(a,stepIndexArray[a-12]),lastButton=getTheButton(a,lastStepArray[a-12]),isMiniLooping[a-12])stepIndexArray[a-12]<startLoopArray[a-12]||stepIndexArray[a-12]>endLoopArray[a-12]||lastStepArray[a-12]<startLoopArray[a-12]||lastStepArray[a-12]>endLoopArray[a-12]||($(currentButton).removeClass("loop").addClass("active"),$(lastButton).removeClass("active").addClass("loop"));else if(isBeingDraggedIn[a-12]){var b=workingMiniLoop.indexOf(stepIndexArray[a-
12]),c=workingMiniLoop.indexOf(lastStepArray[a-12]);-1===b&&-1===c?($(currentButton).addClass("active"),$(lastButton).removeClass("active")):-1!=b&&-1===c?($(currentButton).removeClass("loop").addClass("active"),$(lastButton).removeClass("active")):-1===b&&-1!=c?($(currentButton).addClass("active"),$(lastButton).removeClass("active").addClass("loop")):-1!=b&&-1!=c&&($(currentButton).removeClass("loop").addClass("active"),$(lastButton).removeClass("active").addClass("loop"))}else $(currentButton).addClass("active"),
$(lastButton).removeClass("active")}
function initPattern(a){$(".active").each(function(){$(this).removeClass("active")});if(a)for(a=0;a<fxOnArray.length;a++)thisLight=getTheDumpButton(a),fxOnArray[a]?$(thisLight).removeClass("dumped").addClass("dump"):$(thisLight).addClass("dumped").removeClass("dump");else{filterMax=$(".filterFreq").attr("min");$(".delayFeedbackGain").attr("value",100*feedbackGainArray[showPattern]);$(".delayTime").attr("value",100*delayTimeArray[showPattern]);$(".filterFreq").attr("value",filterFreqArray[showPattern]/
5E3);$(".filterQ").attr("value",filterQArray[showPattern]/5);$(".overdriveFeedback").attr("value",overdriveFeedbackArray[showPattern]);$("#delayTime").html("Time: "+delayTimeArray[showPattern]+"s");$("#delayFeedback").html("Feedback: "+100*feedbackGainArray[showPattern]+"%");$("#filterFrequency").html("Freq: "+filterFreqArray[showPattern].toFixed(0)+"hz");$("#filterQ").html("Q: "+2*filterQArray[showPattern]+"%");$("#overdriveFeedback").html("Amount: "+100*(overdriveFeedbackArray[showPattern]/0.95)+
"%");delayOnArray[showPattern]&&$("#fx0").hasClass("activeFx")?$("#fx0").addClass("fx").removeClass("activeFx"):!delayOnArray[showPattern]&&$("#fx0").hasClass("fx")&&$("#fx0").addClass("activeFx").removeClass("fx");filterOnArray[showPattern]&&$("#fx1").hasClass("activeFx")?$("#fx1").addClass("fx").removeClass("activeFx"):!filterOnArray[showPattern]&&$("#fx1").hasClass("fx")&&$("#fx1").addClass("activeFx").removeClass("fx");overdriveOnArray[showPattern]&&$("#fx2").hasClass("activeFx")?$("#fx2").addClass("fx").removeClass("activeFx"):
!overdriveOnArray[showPattern]&&$("#fx2").hasClass("fx")&&$("#fx2").addClass("activeFx").removeClass("fx");delayOnArray[showPattern]?$("#delayOn").html("Delay: On"):$("#delayOn").html("Delay: Off");filterOnArray[showPattern]?$("#filterOn").html("Filter: On"):$("#filterOn").html("Filter: Off");overdriveOnArray[showPattern]?$("#overdriveOn").html("Overdrive: On"):$("#overdriveOn").html("Overdrive: Off");fxOnArray[showPattern]?($("#fxOn").html("Effects: On"),$("#fx3").addClass("fx").removeClass("activeFx")):
($("#fxOn").html("Effects: Off"),$("#fx3").addClass("activeFx").removeClass("fx"));for(a=0;a<rhythmArray0.length;a++)for(var b=0;b<a1Array.length;b++)currentButton=getTheButton(a,b),allRhythms[showPattern][a][b]&&$(currentButton).addClass("active")}}
function stepJump(){lightToTurnOff=getTheButton($(this).prop("rowIndex")+12,stepIndexArray[$(this).prop("rowIndex")]-1);$(lightToTurnOff).removeClass("active");stepIndexArray[$(this).prop("rowIndex")]=$(this).prop("columnIndex");startLoopArray[$(this).prop("rowIndex")]=0;endLoopArray[$(this).prop("rowIndex")]=15;isMiniLooping[$(this).prop("rowIndex")]=!1}
function startRowDrag(){var a=$(this).prop("rowIndex"),b=$(this).prop("columnIndex");rowAffected=a;workingMiniLoop=[b];isBeingDraggedIn[a]=!0;turnOffThisRow=a;mightJumpToHere=b;$(this).hasClass("punch")?$(this).addClass("loop"):$(this).hasClass("active");$(this).bind("mouseup",escapeRowDrag);$(window).bind("mouseup",escapeRowDrag);for(b=0;16>b;b++)$(getTheButton(a+12,b)).bind("mouseover",addRowDrag).bind("mouseup",endRowDrag)}
function addRowDrag(){var a=$(this).prop("columnIndex"),b;$(this).addClass("loop").bind("mousedown",startRowDrag);$(workingMiniLoop).each(function(a){$(getTheButton(rowAffected+12,workingMiniLoop[a])).removeClass("loop").addClass("punch")});workingMiniLoop=[mightJumpToHere];if(a>workingMiniLoop[0]){b=a;for(i=0;i<a-workingMiniLoop[0];i++)workingMiniLoop.push(b),b--}else{b=a;for(i=0;i<workingMiniLoop[0]-a;i++)workingMiniLoop.push(b),b++}$(workingMiniLoop).each(function(a){$(getTheButton(rowAffected+
12,workingMiniLoop[a])).addClass("loop")})}
function escapeRowDrag(){workingMiniLoop!==[]&&$(workingMiniLoop).each(function(a){$(getTheButton(rowAffected+12,workingMiniLoop[a])).hasClass("loop")?$(getTheButton(rowAffected+12,workingMiniLoop[a])).removeClass("loop").addClass("punch"):$(getTheButton(rowAffected+12,workingMiniLoop[a])).removeClass("active").addClass("punch")});$(isBeingDraggedIn).each(function(a){isBeingDraggedIn[a]=!1});$(window).unbind("mouseup",escapeRowDrag);$(this).removeClass("loop").addClass("punch");for(var a=0;16>a;a++)$(getTheButton(turnOffThisRow+
12,a)).unbind("mouseover",addRowDrag)}
function endRowDrag(){lightToTurnOff=getTheButton($(this).prop("rowIndex")+12,lastStepArray[$(this).prop("rowIndex")]+1);$(lightToTurnOff).removeClass("active");row=$(this).prop("rowIndex");column=$(this).prop("columnIndex");isBeingDraggedIn[row]=!1;isMiniLooping[row]=!0;mightJumpToHere>column?(startLoopArray[row]=column,endLoopArray[row]=mightJumpToHere,stepIndexArray[row]=column):(startLoopArray[row]=mightJumpToHere,endLoopArray[row]=column,stepIndexArray[row]=mightJumpToHere);-1!=workingMiniLoop.indexOf(lastStepArray[row])?
$(getTheButton(row+12,lastStepArray[row])).removeClass("active").addClass("loop"):$(getTheButton(row+12,lastStepArray[row])).removeClass("active").addClass("punch");lastStepArray[row]=stepIndexArray[row]-1;$(window).unbind("mouseup",escapeRowDrag);for(var a=0;16>a;a++)$(getTheButton(turnOffThisRow+12,a)).each(function(){$(this).unbind("mouseover",addRowDrag).unbind("mouseup",endRowDrag)});$(miniLoops[rowAffected]).each(function(a){var c=workingMiniLoop.indexOf(miniLoops[rowAffected][a]);$(getTheButton(rowAffected+
12,miniLoops[rowAffected][a])).hasClass("loop")&&c===-1?$(getTheButton(rowAffected+12,miniLoops[rowAffected][a])).removeClass("loop").addClass("punch"):$(getTheButton(rowAffected+12,miniLoops[rowAffected][a])&&c!=-1).hasClass("punch")?$(getTheButton(rowAffected+12,miniLoops[rowAffected][a])).removeClass("loop").addClass("punch"):$(getTheButton(rowAffected+12,miniLoops[rowAffected][a])).removeClass("active").addClass("punch")});miniLoops[row]=workingMiniLoop}
function getTheButton(a,b){rowA=[document.getElementById("a0"),document.getElementById("a1"),document.getElementById("a2"),document.getElementById("a3"),document.getElementById("a4"),document.getElementById("a5"),document.getElementById("a6"),document.getElementById("a7"),document.getElementById("a8"),document.getElementById("a9"),document.getElementById("a10"),document.getElementById("a11"),document.getElementById("a12"),document.getElementById("a13"),document.getElementById("a14"),document.getElementById("a15")];
rowB=[document.getElementById("b0"),document.getElementById("b1"),document.getElementById("b2"),document.getElementById("b3"),document.getElementById("b4"),document.getElementById("b5"),document.getElementById("b6"),document.getElementById("b7"),document.getElementById("b8"),document.getElementById("b9"),document.getElementById("b10"),document.getElementById("b11"),document.getElementById("b12"),document.getElementById("b13"),document.getElementById("b14"),document.getElementById("b15")];rowC=[document.getElementById("c0"),
document.getElementById("c1"),document.getElementById("c2"),document.getElementById("c3"),document.getElementById("c4"),document.getElementById("c5"),document.getElementById("c6"),document.getElementById("c7"),document.getElementById("c8"),document.getElementById("c9"),document.getElementById("c10"),document.getElementById("c11"),document.getElementById("c12"),document.getElementById("c13"),document.getElementById("c14"),document.getElementById("c15")];rowD=[document.getElementById("d0"),document.getElementById("d1"),
document.getElementById("d2"),document.getElementById("d3"),document.getElementById("d4"),document.getElementById("d5"),document.getElementById("d6"),document.getElementById("d7"),document.getElementById("d8"),document.getElementById("d9"),document.getElementById("d10"),document.getElementById("d11"),document.getElementById("d12"),document.getElementById("d13"),document.getElementById("d14"),document.getElementById("d15")];rowE=[document.getElementById("e0"),document.getElementById("e1"),document.getElementById("e2"),
document.getElementById("e3"),document.getElementById("e4"),document.getElementById("e5"),document.getElementById("e6"),document.getElementById("e7"),document.getElementById("e8"),document.getElementById("e9"),document.getElementById("e10"),document.getElementById("e11"),document.getElementById("e12"),document.getElementById("e13"),document.getElementById("e14"),document.getElementById("e15")];rowF=[document.getElementById("f0"),document.getElementById("f1"),document.getElementById("f2"),document.getElementById("f3"),
document.getElementById("f4"),document.getElementById("f5"),document.getElementById("f6"),document.getElementById("f7"),document.getElementById("f8"),document.getElementById("f9"),document.getElementById("f10"),document.getElementById("f11"),document.getElementById("f12"),document.getElementById("f13"),document.getElementById("f14"),document.getElementById("f15")];rowG=[document.getElementById("g0"),document.getElementById("g1"),document.getElementById("g2"),document.getElementById("g3"),document.getElementById("g4"),
document.getElementById("g5"),document.getElementById("g6"),document.getElementById("g7"),document.getElementById("g8"),document.getElementById("g9"),document.getElementById("g10"),document.getElementById("g11"),document.getElementById("g12"),document.getElementById("g13"),document.getElementById("g14"),document.getElementById("g15")];rowH=[document.getElementById("h0"),document.getElementById("h1"),document.getElementById("h2"),document.getElementById("h3"),document.getElementById("h4"),document.getElementById("h5"),
document.getElementById("h6"),document.getElementById("h7"),document.getElementById("h8"),document.getElementById("h9"),document.getElementById("h10"),document.getElementById("h11"),document.getElementById("h12"),document.getElementById("h13"),document.getElementById("h14"),document.getElementById("h15")];rowI=[document.getElementById("i0"),document.getElementById("i1"),document.getElementById("i2"),document.getElementById("i3"),document.getElementById("i4"),document.getElementById("i5"),document.getElementById("i6"),
document.getElementById("i7"),document.getElementById("i8"),document.getElementById("i9"),document.getElementById("i10"),document.getElementById("i11"),document.getElementById("i12"),document.getElementById("i13"),document.getElementById("i14"),document.getElementById("i15")];rowJ=[document.getElementById("j0"),document.getElementById("j1"),document.getElementById("j2"),document.getElementById("j3"),document.getElementById("j4"),document.getElementById("j5"),document.getElementById("j6"),document.getElementById("j7"),
document.getElementById("j8"),document.getElementById("j9"),document.getElementById("j10"),document.getElementById("j11"),document.getElementById("j12"),document.getElementById("j13"),document.getElementById("j14"),document.getElementById("j15")];rowK=[document.getElementById("k0"),document.getElementById("k1"),document.getElementById("k2"),document.getElementById("k3"),document.getElementById("k4"),document.getElementById("k5"),document.getElementById("k6"),document.getElementById("k7"),document.getElementById("k8"),
document.getElementById("k9"),document.getElementById("k10"),document.getElementById("k11"),document.getElementById("k12"),document.getElementById("k13"),document.getElementById("k14"),document.getElementById("k15")];rowL=[document.getElementById("l0"),document.getElementById("l1"),document.getElementById("l2"),document.getElementById("l3"),document.getElementById("l4"),document.getElementById("l5"),document.getElementById("l6"),document.getElementById("l7"),document.getElementById("l8"),document.getElementById("l9"),
document.getElementById("l10"),document.getElementById("l11"),document.getElementById("l12"),document.getElementById("l13"),document.getElementById("l14"),document.getElementById("l15")];rowAA=[document.getElementById("aa0"),document.getElementById("aa1"),document.getElementById("aa2"),document.getElementById("aa3"),document.getElementById("aa4"),document.getElementById("aa5"),document.getElementById("aa6"),document.getElementById("aa7"),document.getElementById("aa8"),document.getElementById("aa9"),
document.getElementById("aa10"),document.getElementById("aa11"),document.getElementById("aa12"),document.getElementById("aa13"),document.getElementById("aa14"),document.getElementById("aa15")];rowBB=[document.getElementById("bb0"),document.getElementById("bb1"),document.getElementById("bb2"),document.getElementById("bb3"),document.getElementById("bb4"),document.getElementById("bb5"),document.getElementById("bb6"),document.getElementById("bb7"),document.getElementById("bb8"),document.getElementById("bb9"),
document.getElementById("bb10"),document.getElementById("bb11"),document.getElementById("bb12"),document.getElementById("bb13"),document.getElementById("bb14"),document.getElementById("bb15")];rowCC=[document.getElementById("cc0"),document.getElementById("cc1"),document.getElementById("cc2"),document.getElementById("cc3"),document.getElementById("cc4"),document.getElementById("cc5"),document.getElementById("cc6"),document.getElementById("cc7"),document.getElementById("cc8"),document.getElementById("cc9"),
document.getElementById("cc10"),document.getElementById("cc11"),document.getElementById("cc12"),document.getElementById("cc13"),document.getElementById("cc14"),document.getElementById("cc15")];rowDD=[document.getElementById("dd0"),document.getElementById("dd1"),document.getElementById("dd2"),document.getElementById("dd3"),document.getElementById("dd4"),document.getElementById("dd5"),document.getElementById("dd6"),document.getElementById("dd7"),document.getElementById("dd8"),document.getElementById("dd9"),
document.getElementById("dd10"),document.getElementById("dd11"),document.getElementById("dd12"),document.getElementById("dd13"),document.getElementById("dd14"),document.getElementById("dd15")];rowEE=[document.getElementById("ee0"),document.getElementById("ee1"),document.getElementById("ee2"),document.getElementById("ee3"),document.getElementById("ee4"),document.getElementById("ee5"),document.getElementById("ee6"),document.getElementById("ee7"),document.getElementById("ee8"),document.getElementById("ee9"),
document.getElementById("ee10"),document.getElementById("ee11"),document.getElementById("ee12"),document.getElementById("ee13"),document.getElementById("ee14"),document.getElementById("ee15")];rowFF=[document.getElementById("ff0"),document.getElementById("ff1"),document.getElementById("ff2"),document.getElementById("ff3"),document.getElementById("ff4"),document.getElementById("ff5"),document.getElementById("ff6"),document.getElementById("ff7"),document.getElementById("ff8"),document.getElementById("ff9"),
document.getElementById("ff10"),document.getElementById("ff11"),document.getElementById("ff12"),document.getElementById("ff13"),document.getElementById("ff14"),document.getElementById("ff15")];rowGG=[document.getElementById("gg0"),document.getElementById("gg1"),document.getElementById("gg2"),document.getElementById("gg3"),document.getElementById("gg4"),document.getElementById("gg5"),document.getElementById("gg6"),document.getElementById("gg7"),document.getElementById("gg8"),document.getElementById("gg9"),
document.getElementById("gg10"),document.getElementById("gg11"),document.getElementById("gg12"),document.getElementById("gg13"),document.getElementById("gg14"),document.getElementById("gg15")];rowHH=[document.getElementById("hh0"),document.getElementById("hh1"),document.getElementById("hh2"),document.getElementById("hh3"),document.getElementById("hh4"),document.getElementById("hh5"),document.getElementById("hh6"),document.getElementById("hh7"),document.getElementById("hh8"),document.getElementById("hh9"),
document.getElementById("hh10"),document.getElementById("hh11"),document.getElementById("hh12"),document.getElementById("hh13"),document.getElementById("hh14"),document.getElementById("hh15")];rowII=[document.getElementById("ii0"),document.getElementById("ii1"),document.getElementById("ii2"),document.getElementById("ii3"),document.getElementById("ii4"),document.getElementById("ii5"),document.getElementById("ii6"),document.getElementById("ii7"),document.getElementById("ii8"),document.getElementById("ii9"),
document.getElementById("ii10"),document.getElementById("ii11"),document.getElementById("ii12"),document.getElementById("ii13"),document.getElementById("ii14"),document.getElementById("ii15")];rowJJ=[document.getElementById("jj0"),document.getElementById("jj1"),document.getElementById("jj2"),document.getElementById("jj3"),document.getElementById("jj4"),document.getElementById("jj5"),document.getElementById("jj6"),document.getElementById("jj7"),document.getElementById("jj8"),document.getElementById("jj9"),
document.getElementById("jj10"),document.getElementById("jj11"),document.getElementById("jj12"),document.getElementById("jj13"),document.getElementById("jj14"),document.getElementById("jj15")];rowKK=[document.getElementById("kk0"),document.getElementById("kk1"),document.getElementById("kk2"),document.getElementById("kk3"),document.getElementById("kk4"),document.getElementById("kk5"),document.getElementById("kk6"),document.getElementById("kk7"),document.getElementById("kk8"),document.getElementById("kk9"),
document.getElementById("kk10"),document.getElementById("kk11"),document.getElementById("kk12"),document.getElementById("kk13"),document.getElementById("kk14"),document.getElementById("kk15")];rowLL=[document.getElementById("ll0"),document.getElementById("ll1"),document.getElementById("ll2"),document.getElementById("ll3"),document.getElementById("ll4"),document.getElementById("ll5"),document.getElementById("ll6"),document.getElementById("ll7"),document.getElementById("ll8"),document.getElementById("ll9"),
document.getElementById("ll10"),document.getElementById("ll11"),document.getElementById("ll12"),document.getElementById("ll13"),document.getElementById("ll14"),document.getElementById("ll15")];rowArray=[rowA,rowB,rowC,rowD,rowE,rowF,rowG,rowH,rowI,rowJ,rowK,rowL,rowAA,rowBB,rowCC,rowDD,rowEE,rowFF,rowGG,rowHH,rowII,rowJJ,rowKK,rowLL];return rowArray[a][b]}
function getTheDumpButton(a){dumpArray=[document.getElementById("aaD"),document.getElementById("bbD"),document.getElementById("ccD"),document.getElementById("ddD"),document.getElementById("eeD"),document.getElementById("ffD"),document.getElementById("ggD"),document.getElementById("hhD")];return dumpArray[a]}
function getTheMuteButton(a){muteButtonArray=[document.getElementById("aaM"),document.getElementById("bbM"),document.getElementById("ccM"),document.getElementById("ddM"),document.getElementById("eeM"),document.getElementById("ffM"),document.getElementById("ggM"),document.getElementById("hhM")];return muteButtonArray[a]};